// Enhanced Template System with more options and customization

import { TemplateConfig } from '@/types/template';

export const TEMPLATES: TemplateConfig[] = [
  {
    id: 'love',
    name: 'Love',
    icon: '💕',
    description: 'Warm, romantic, heart motifs - Perfect for expressing deep affection',
    colorTheme: 'warm',
    gradient: 'from-rose-500 via-pink-500 to-red-500',
    fields: [
      {
        name: 'sender',
        label: 'Your Name',
        type: 'text',
        placeholder: 'Enter your name',
        required: true,
        maxLength: 50,
      },
      {
        name: 'receiver',
        label: "Recipient's Name",
        type: 'text',
        placeholder: 'Who is this for?',
        required: true,
        maxLength: 50,
      },
      {
        name: 'message',
        label: 'Your Message',
        type: 'textarea',
        placeholder: 'Pour your heart out...',
        required: true,
        minLength: 10,
        maxLength: 2000,
      },
    ],
  },
  {
    id: 'sorry',
    name: 'Sorry',
    icon: '🌿',
    description: 'Calm, respectful, clean lines - For heartfelt apologies',
    colorTheme: 'calm',
    gradient: 'from-sky-500 via-blue-500 to-cyan-600',
    fields: [
      {
        name: 'sender',
        label: 'Your Name',
        type: 'text',
        placeholder: 'Enter your name',
        required: true,
        maxLength: 50,
      },
      {
        name: 'receiver',
        label: "Recipient's Name",
        type: 'text',
        placeholder: 'Who are you apologizing to?',
        required: true,
        maxLength: 50,
      },
      {
        name: 'message',
        label: 'Your Apology',
        type: 'textarea',
        placeholder: 'Speak from the heart...',
        required: true,
        minLength: 10,
        maxLength: 2000,
      },
    ],
  },
  {
    id: 'birthday',
    name: 'Birthday',
    icon: '🎂',
    description: 'Playful, bright, celebratory - Make their day unforgettable',
    colorTheme: 'bright',
    gradient: 'from-amber-500 via-yellow-500 to-orange-600',
    fields: [
      {
        name: 'sender',
        label: 'Your Name',
        type: 'text',
        placeholder: 'Enter your name',
        required: true,
        maxLength: 50,
      },
      {
        name: 'receiver',
        label: 'Birthday Person',
        type: 'text',
        placeholder: 'Who is celebrating?',
        required: true,
        maxLength: 50,
      },
      {
        name: 'message',
        label: 'Birthday Wishes',
        type: 'textarea',
        placeholder: 'Make their day special...',
        required: true,
        minLength: 10,
        maxLength: 2000,
      },
    ],
  },
  {
    id: 'gratitude',
    name: 'Thank You',
    icon: '🙏',
    description: 'Elegant, appreciative, warm - Express your gratitude beautifully',
    colorTheme: 'warm',
    gradient: 'from-emerald-500 via-teal-500 to-green-600',
    fields: [
      {
        name: 'sender',
        label: 'Your Name',
        type: 'text',
        placeholder: 'Enter your name',
        required: true,
        maxLength: 50,
      },
      {
        name: 'receiver',
        label: "Recipient's Name",
        type: 'text',
        placeholder: 'Who are you thanking?',
        required: true,
        maxLength: 50,
      },
      {
        name: 'message',
        label: 'Your Thanks',
        type: 'textarea',
        placeholder: 'Express your gratitude...',
        required: true,
        minLength: 10,
        maxLength: 2000,
      },
    ],
  },
  {
    id: 'congratulations',
    name: 'Congratulations',
    icon: '🎉',
    description: 'Vibrant, exciting, celebratory - Celebrate their achievements',
    colorTheme: 'bright',
    gradient: 'from-purple-500 via-fuchsia-500 to-pink-600',
    fields: [
      {
        name: 'sender',
        label: 'Your Name',
        type: 'text',
        placeholder: 'Enter your name',
        required: true,
        maxLength: 50,
      },
      {
        name: 'receiver',
        label: "Recipient's Name",
        type: 'text',
        placeholder: 'Who achieved something great?',
        required: true,
        maxLength: 50,
      },
      {
        name: 'message',
        label: 'Your Congratulations',
        type: 'textarea',
        placeholder: 'Celebrate their success...',
        required: true,
        minLength: 10,
        maxLength: 2000,
      },
    ],
  },
  {
    id: 'encouragement',
    name: 'Encouragement',
    icon: '💪',
    description: 'Uplifting, supportive, motivating - Inspire and support',
    colorTheme: 'calm',
    gradient: 'from-indigo-500 via-blue-500 to-purple-600',
    fields: [
      {
        name: 'sender',
        label: 'Your Name',
        type: 'text',
        placeholder: 'Enter your name',
        required: true,
        maxLength: 50,
      },
      {
        name: 'receiver',
        label: "Recipient's Name",
        type: 'text',
        placeholder: 'Who needs encouragement?',
        required: true,
        maxLength: 50,
      },
      {
        name: 'message',
        label: 'Your Encouragement',
        type: 'textarea',
        placeholder: 'Lift their spirits...',
        required: true,
        minLength: 10,
        maxLength: 2000,
      },
    ],
  },
  {
    id: 'miss-you',
    name: 'Miss You',
    icon: '💭',
    description: 'Nostalgic, tender, heartfelt - Let them know you care',
    colorTheme: 'warm',
    gradient: 'from-violet-500 via-purple-500 to-indigo-600',
    fields: [
      {
        name: 'sender',
        label: 'Your Name',
        type: 'text',
        placeholder: 'Enter your name',
        required: true,
        maxLength: 50,
      },
      {
        name: 'receiver',
        label: "Recipient's Name",
        type: 'text',
        placeholder: 'Who do you miss?',
        required: true,
        maxLength: 50,
      },
      {
        name: 'message',
        label: 'Your Message',
        type: 'textarea',
        placeholder: 'Tell them how much you miss them...',
        required: true,
        minLength: 10,
        maxLength: 2000,
      },
    ],
  },
  {
    id: 'friendship',
    name: 'Friendship',
    icon: '🤝',
    description: 'Warm, genuine, supportive - Celebrate your bond',
    colorTheme: 'bright',
    gradient: 'from-orange-500 via-amber-500 to-yellow-600',
    fields: [
      {
        name: 'sender',
        label: 'Your Name',
        type: 'text',
        placeholder: 'Enter your name',
        required: true,
        maxLength: 50,
      },
      {
        name: 'receiver',
        label: "Friend's Name",
        type: 'text',
        placeholder: 'Your friend',
        required: true,
        maxLength: 50,
      },
      {
        name: 'message',
        label: 'Your Message',
        type: 'textarea',
        placeholder: 'Celebrate your friendship...',
        required: true,
        minLength: 10,
        maxLength: 2000,
      },
    ],
  },
  {
    id: 'get-well',
    name: 'Get Well Soon',
    icon: '🌸',
    description: 'Gentle, caring, hopeful - Send healing wishes',
    colorTheme: 'calm',
    gradient: 'from-pink-400 via-rose-400 to-red-400',
    fields: [
      {
        name: 'sender',
        label: 'Your Name',
        type: 'text',
        placeholder: 'Enter your name',
        required: true,
        maxLength: 50,
      },
      {
        name: 'receiver',
        label: "Recipient's Name",
        type: 'text',
        placeholder: 'Who needs healing?',
        required: true,
        maxLength: 50,
      },
      {
        name: 'message',
        label: 'Your Wishes',
        type: 'textarea',
        placeholder: 'Send your healing thoughts...',
        required: true,
        minLength: 10,
        maxLength: 2000,
      },
    ],
  },
];

export const getTemplateById = (id: string): TemplateConfig | undefined => {
  return TEMPLATES.find((t) => t.id === id);
};

export const getTemplatesByCategory = (category: string): TemplateConfig[] => {
  return TEMPLATES.filter((t) => t.colorTheme === category);
};
